#ifndef _MAPSERVER_VERSION_H
#define _MAPSERVER_VERSION_H

#define MS_VERSION_MAJOR 6
#define MS_VERSION_MINOR 4
#define MS_VERSION_REV 3
#define MS_VERSION "6.4.3"
#define MS_VERSION_NUM  60403 

#endif

