#ifndef DEFINES_H

#define DEFINES_H



#define FNSIZE 256

#define MAX_SPECIES 30

#define MAX_LANDUNITS 65535 //Changed on Jan 15 2009

#define MAX_RECLASS 50



#define G_SUCCESSION			1	//0x0000001 

#define G_BDA					2   //0x0000010

#define G_WIND					4   //0x0000100 

#define G_HARVEST				8	//0x0001000

#define G_FUEL					16  //0x0010000

#define G_FIRE					32  //0x0100000

#define	G_BGROWTH				64  //0x1000000

#define	G_FUELMANAGEMENT		128 //0x10000000

//const int G_SUCCESSION = 1;//0x0000001 

//const int G_BDA = 2; //0x0000010

//const int G_WIND = 4; //0x0000100 

//const int G_HARVEST = 8; //0x0001000

//const int G_FUEL = 16; //0x0010000

//const int G_FIRE = 32; //0x0100000

//const int G_BGROWTH = 64; //0x1000000

//const int G_FUELMANAGEMENT = 128; //0x10000000

#endif